name: Matrix Demo
on: [workflow_dispatch]
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16, 18]
        operation-system: [ubuntu-latest, windows-latest]

        include: 
          - node-version: 19
            operation-system: ubuntu-latest

        exclude: 
          - node-version: 18
            operation-system: windows-latest

    runs-on: ${{ matrix.operation-system }}
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{  matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build
